export const GET_CONTACTS_LOAD = "GET_CONTACTS_LOAD";
export const GET_CONTACTS_SUCESS = "GET_CONTACTS_SUCESS";
export const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL";

export const ADD_CONTACT_FAIL = "ADD_CONTACT_FAIL";

export const DELETE_CONTACT_SUCESS = "DELETE_CONTACT_SUCESS";
export const DELETE_CONTACT_FAIL = "DELETE_CONTACT_FAIL";

export const GET_CONTACT_LOAD = "GET_CONTACT_LOAD";
export const GET_CONTACT_SUCESS = "GET_CONTACT_SUCESS";
export const GET_CONTACT_FAIL = "GET_CONTACT_FAILD";

export const TOGGLE_TRUE = "TOGGLE_TRUE";
export const TOGGLE_FALSE = "TOGGLE_FALSE";

export const EDIT_CONTACT_SUCESS = "EDIT_CONTACT_SUCESS";
export const EDIT_CONTACT_FAIL = "EDIT_CONTACT_FAIL";
